import type { ReadonlyScheduleFixture } from './readonly-schedule.types'

export const readonlyScheduleMockFixture: ReadonlyScheduleFixture = {
  tournaments: [
    {
      id: 'tournament-campus-cup-2026',
      name: '2026 华师校园足球杯',
      code: 'CAMPUS-CUP-2026',
      seasonName: '2026 春季赛',
      organizationName: '晓球开发组织',
      statusText: '赛程已发布',
      startDate: '2026-07-01',
      endDate: '2026-07-18',
      teamCount: 16,
      matchCount: 31,
      description: '16 支学院球队，4 个小组单循环后晋级 8 强淘汰赛。',
      rules: ['小组赛胜 3 分、平 1 分、负 0 分。', '每组前两名晋级八强。', '淘汰赛平局进入点球。'],
      teams: [
        {
          id: 'team-green',
          tournamentId: 'tournament-campus-cup-2026',
          name: '绿茵学院',
          shortName: '绿茵',
          groupName: 'A 组',
          coachName: '陈指导',
          captainName: '林远',
          colors: '深绿 / 白',
          rosterPreview: ['林远', '周野', '何川', '唐宁'],
        },
        {
          id: 'team-spark',
          tournamentId: 'tournament-campus-cup-2026',
          name: '星火学院',
          shortName: '星火',
          groupName: 'A 组',
          coachName: '许指导',
          captainName: '赵明',
          colors: '红 / 黑',
          rosterPreview: ['赵明', '邱白', '陆南', '梁一'],
        },
        {
          id: 'team-river',
          tournamentId: 'tournament-campus-cup-2026',
          name: '江湾联队',
          shortName: '江湾',
          groupName: 'B 组',
          coachName: '吴指导',
          captainName: '沈澄',
          colors: '蓝 / 白',
          rosterPreview: ['沈澄', '顾北', '罗星', '叶舟'],
        },
      ],
      recentMatches: [
        {
          id: 'match-001',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '小组赛',
          groupName: 'A 组',
          roundName: '第 1 轮',
          scheduledStartAt: '2026-07-01T10:00:00+08:00',
          venueName: '东区足球场',
          pitchName: '1 号场',
          homeTeamId: 'team-green',
          awayTeamId: 'team-spark',
          homeTeamName: '绿茵学院',
          awayTeamName: '星火学院',
          status: 'SCHEDULED',
        },
        {
          id: 'match-002',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '小组赛',
          groupName: 'B 组',
          roundName: '第 1 轮',
          scheduledStartAt: '2026-07-01T15:30:00+08:00',
          venueName: '东区足球场',
          pitchName: '2 号场',
          homeTeamId: 'team-river',
          awayTeamId: 'team-green',
          homeTeamName: '江湾联队',
          awayTeamName: '绿茵学院',
          status: 'SCHEDULED',
        },
        {
          id: 'match-003',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '小组赛',
          groupName: 'A 组',
          roundName: '第 2 轮',
          scheduledStartAt: '2026-07-02T09:30:00+08:00',
          venueName: '西区体育中心',
          pitchName: '主场',
          homeTeamId: 'team-spark',
          awayTeamId: 'team-river',
          homeTeamName: '星火学院',
          awayTeamName: '江湾联队',
          status: 'CANCELLED',
          statusReason: '雷雨预警，等待重新排期',
        },
        {
          id: 'match-004',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '八强赛',
          roundName: '1/4 决赛',
          scheduledStartAt: '2026-07-12T19:00:00+08:00',
          venueName: '东区足球场',
          pitchName: '1 号场',
          homeTeamId: 'team-green',
          awayTeamId: 'team-river',
          homeTeamName: 'A1',
          awayTeamName: 'B2',
          status: 'SCHEDULED',
        },
      ],
    },
  ],
}
