import type {
  ReadonlyScheduleFixture,
  ReadonlyTeam,
  ReadonlyTeamSummary,
} from './readonly-schedule.types'

const teamDetails: ReadonlyTeam[] = [
  {
    id: 'team-green',
    tournamentId: 'tournament-campus-cup-2026',
    teamCode: 'GREEN-01',
    name: '绿茵学院',
    shortName: '绿茵',
    registrationStatus: 'APPROVED',
    rosterStatus: 'LOCKED',
    rosterPlayerCount: 5,
    leaderDisplayName: '林远',
    coachDisplayName: '陈指导',
    rosterSnapshotVersion: 2,
    players: [
      { id: 'player-green-01', displayName: '林远', shirtNumber: '01' },
      { id: 'player-green-02', displayName: '周野', shirtNumber: '7' },
      { id: 'player-green-03', displayName: '何川', shirtNumber: '10' },
      { id: 'player-green-04', displayName: '唐宁', shirtNumber: '18' },
      { id: 'player-green-05', displayName: '顾航', shirtNumber: null },
    ],
  },
  {
    id: 'team-spark',
    tournamentId: 'tournament-campus-cup-2026',
    teamCode: 'SPARK-02',
    name: '星火学院',
    shortName: '星火',
    registrationStatus: 'APPROVED',
    rosterStatus: 'LOCKED',
    rosterPlayerCount: 5,
    leaderDisplayName: '赵明',
    coachDisplayName: '许指导',
    rosterSnapshotVersion: 1,
    players: [
      { id: 'player-spark-01', displayName: '赵明', shirtNumber: '9' },
      { id: 'player-spark-02', displayName: '邱白', shirtNumber: '11' },
      { id: 'player-spark-03', displayName: '陆南', shirtNumber: '16' },
      { id: 'player-spark-04', displayName: '梁一', shirtNumber: '21' },
      { id: 'player-spark-05', displayName: '夏树', shirtNumber: null },
    ],
  },
  {
    id: 'team-river',
    tournamentId: 'tournament-campus-cup-2026',
    teamCode: 'RIVER-03',
    name: '江湾联队',
    shortName: '江湾',
    registrationStatus: 'APPROVED',
    rosterStatus: 'LOCKED',
    rosterPlayerCount: 5,
    leaderDisplayName: '沈澄',
    coachDisplayName: '吴指导',
    rosterSnapshotVersion: 3,
    players: [
      { id: 'player-river-01', displayName: '沈澄', shirtNumber: '4' },
      { id: 'player-river-02', displayName: '顾北', shirtNumber: '6' },
      { id: 'player-river-03', displayName: '罗星', shirtNumber: '12' },
      { id: 'player-river-04', displayName: '叶舟', shirtNumber: '20' },
      { id: 'player-river-05', displayName: '秦越', shirtNumber: null },
    ],
  },
  {
    id: 'team-southwind',
    tournamentId: 'tournament-campus-cup-2026',
    teamCode: 'WIND-04',
    name: '南风竞技',
    shortName: '南风',
    registrationStatus: 'APPROVED',
    rosterStatus: 'LOCKED',
    rosterPlayerCount: 5,
    leaderDisplayName: '程风',
    coachDisplayName: null,
    rosterSnapshotVersion: 1,
    players: [
      { id: 'player-wind-01', displayName: '程风', shirtNumber: '8' },
      { id: 'player-wind-02', displayName: '苏遥', shirtNumber: '13' },
      { id: 'player-wind-03', displayName: '许原', shirtNumber: '19' },
      { id: 'player-wind-04', displayName: '江澈', shirtNumber: '23' },
      { id: 'player-wind-05', displayName: '方临', shirtNumber: null },
    ],
  },
]

export const readonlyScheduleMockFixture: ReadonlyScheduleFixture = {
  tournaments: [
    {
      id: 'tournament-campus-cup-2026',
      name: '2026 华师校园足球杯',
      code: 'CAMPUS-CUP-2026',
      seasonName: '2026 秋季赛',
      organizationName: '晓球开发组织',
      statusText: '赛程已发布',
      startDate: '2026-09-05',
      endDate: '2026-09-20',
      teamCount: teamDetails.length,
      matchCount: 6,
      description: '学院球队先进行小组循环，再进入淘汰赛阶段。',
      rules: [
        '小组赛胜 3 分、平 1 分、负 0 分。',
        '小组前两名进入淘汰赛。',
        '淘汰赛平局进入点球。',
      ],
      teams: teamDetails.map(toTeamSummary),
      recentMatches: [
        {
          id: 'match-001',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '小组赛',
          groupName: 'A 组',
          roundName: '第 1 轮',
          scheduledStartAt: '2026-09-05T10:00:00+08:00',
          venueName: '东区足球场',
          pitchName: '1 号场',
          homeTeamId: 'team-green',
          awayTeamId: 'team-spark',
          homeTeamName: '绿茵学院',
          awayTeamName: '星火学院',
          status: 'LIVE',
        },
        {
          id: 'match-002',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '小组赛',
          groupName: 'A 组',
          roundName: '第 1 轮',
          scheduledStartAt: '2026-09-05T15:30:00+08:00',
          venueName: '东区足球场',
          pitchName: '2 号场',
          homeTeamId: 'team-river',
          awayTeamId: 'team-southwind',
          homeTeamName: '江湾联队',
          awayTeamName: '南风竞技',
          status: 'SCHEDULED',
        },
        {
          id: 'match-003',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '小组赛',
          groupName: 'A 组',
          roundName: '第 2 轮',
          scheduledStartAt: '2026-09-08T18:30:00+08:00',
          venueName: '西区体育中心',
          pitchName: '主场',
          homeTeamId: 'team-spark',
          awayTeamId: 'team-river',
          homeTeamName: '星火学院',
          awayTeamName: '江湾联队',
          status: 'POSTPONED',
          statusReason: '场地调整，具体时间待赛事方确认',
        },
        {
          id: 'match-004',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '小组赛',
          groupName: 'A 组',
          roundName: '第 2 轮',
          scheduledStartAt: '2026-09-09T18:30:00+08:00',
          venueName: '东区足球场',
          pitchName: '1 号场',
          homeTeamId: 'team-southwind',
          awayTeamId: 'team-green',
          homeTeamName: '南风竞技',
          awayTeamName: '绿茵学院',
          status: 'SCHEDULED',
        },
        {
          id: 'match-005',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '半决赛',
          roundName: '半决赛 1',
          scheduledStartAt: '2026-09-16T19:00:00+08:00',
          venueName: '东区足球场',
          pitchName: '1 号场',
          homeTeamId: '',
          awayTeamId: '',
          homeTeamName: 'A 组第 1',
          awayTeamName: 'A 组第 2',
          status: 'SCHEDULED',
        },
        {
          id: 'match-006',
          tournamentId: 'tournament-campus-cup-2026',
          stageName: '决赛',
          roundName: '冠军赛',
          scheduledStartAt: '2026-09-20T19:00:00+08:00',
          venueName: '东区足球场',
          pitchName: '主场',
          homeTeamId: '',
          awayTeamId: '',
          homeTeamName: '半决赛胜者 1',
          awayTeamName: '半决赛胜者 2',
          status: 'SCHEDULED',
        },
      ],
    },
  ],
  teamDetails,
}

function toTeamSummary(team: ReadonlyTeam): ReadonlyTeamSummary {
  return {
    id: team.id,
    tournamentId: team.tournamentId,
    teamCode: team.teamCode,
    name: team.name,
    shortName: team.shortName,
    registrationStatus: team.registrationStatus,
    rosterStatus: team.rosterStatus,
    rosterPlayerCount: team.rosterPlayerCount,
  }
}
